Fanilo | remove 'PBX_HMAC' from the array before hmac compute
adriantombu/packages pull request #13
Opened 2020-12-28 10:25 UTC by Nhilo94

i'm using the paybox system and i found that it doesn't work when the 'PBX_HMAC' is in the string to be computed for its value.
i fix it

2020-12-28 18:21 UTC, adriantombu requested changes

2020-12-28 18:21 UTC, adriantombu commented on packages/paybox-system/src/paybox.ts
> +      const chain = elements.filter(element => element.name !== 'PBX_HMAC')map((e) => `${e.name}=${e.value}`).join('&')
- Please replace `element` by `e` to stay consistent with the naming in `map`
- There's a dot missing in front of the `map` => `'PBX_HMAC').map` 😀

2020-12-28 18:22 UTC, adriantombu commented
Thanks for your submission @Nhilo94 ! There are just a few modifications before I can approve this PR 😊

2020-12-30 08:42 UTC, Nhilo94 commented on packages/paybox-system/src/paybox.ts
> +      const chain = elements.filter(element => element.name !== 'PBX_HMAC')map((e) => `${e.name}=${e.value}`).join('&')
fixed

2020-12-30 22:01 UTC, merged

2020-12-30 22:34 UTC, adriantombu commented
This update is deployed on npm with the version 1.0.14, thanks again!